# Use root/example user/password credentials
version: '2'

services:
  php-social-network:
    image: socialnetwork
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html/
    # networks:
    #   - shared
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    # networks:
    #   - shared
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db

# networks:
#   shared:
#     external: true


