# Use root/example user/password credentials
version: '2'

services:
  php-social-network:
    image: socialnetwork
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html/
    environment:
      MYSQL_DB_CONNECTION: test
      MYSQL_DB_NAME: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      SITE_URL: http://localhost
    networks:
      - test

networks:
  test:
    external: true


